### ISSUE TITLE
Issue in market order - ask

### ISSUE THREAD

**Issue by sanada08** [viabtc/viabtc_exchange_server#196]
In  market order, if I try to buy  "1" amount for any market it empty all other order in the sell.
for example , if I have more than 5 sell order, I have tried to buy in market price, I will buy all other sell orders.

**Comment by codeman-crypto** [comment]
I am also facing the same issue, Say example I am having 10 sell orders and 20 buy orders with different price and the current market price is 0.02.
Now if I  place a market order(buy) using the method `put_market` for the amount `1`
Expected Result: The amount `1` should be matched with the sell orders.
Actual Result: All the sell orders got matched and the sell orders in the order book become empty and the balance has been deducted. 

I am not sure is because of the wrong implementation or actually, it is a bug

**Comment by lealife** [comment]
For buy market order, the amount param means "how much money i want to use", not "how much coins i want to buy"

**Comment by sanada08** [comment]
thanks.
