### ISSUE TITLE
Example of connecting to accessws

### ISSUE THREAD

**Issue by AndrewSamokhvalov** [viabtc/viabtc_exchange_server#27]
Hey guys, does any has the example of connecting to `accessws`? Having trouble in finding the origin of problem. `Wireshark` shows that connecting is stalling on waiting of  first handshake message from `accessws`.  @haipome

**Comment by djpnewton** [comment]
I started an example JS client: https://github.com/djpnewton/viaxchtest/commit/65b849c4fbcae43b4272ab1e749f86156731e520

It uses this change to bind the websocket server to a tcp port: https://github.com/djpnewton/viabtc_exchange_server/commit/4c42bdff4063d06dd07b9f229bbb7b175cf79598

And required (for firefox at least) is this PR: https://github.com/viabtc/viabtc_exchange_server/pull/28

**Comment by AndrewSamokhvalov** [comment]
@djpnewton Thanks! We will try it out.

**Comment by haipome** [comment]
@djpnewton is right, you need change the default config to TCP.

The suggest way is use Nginx as frontend. Example of Nginx config:

`server {
  listen 8008;
  listen 8443 ssl;
  server_name socket.example.com;

  ssl_certificate example.crt;
  ssl_certificate_key example.key;

  location / {
    proxy_pass http://unix:/tmp/accessws.sock;
    proxy_redirect off;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_send_timeout 1d;
    proxy_read_timeout 1d;
    proxy_connect_timeout 1d;
    proxy_set_header X-Real-IP $remote_addr;
  }
}`

**Comment by djpnewton** [comment]
Yes I guess if you use Nginx as a reverse proxy and overwrite the `Connection` header then you would not need PR #28 

I have added a section to the readme file about websocket authorization #30

**Comment by haipome** [comment]
@djpnewton Good job.

**Comment by thotheolh** [comment]
I am using the same configuration as above with an Nginx server

This is the Nginx configuration:

```
# Configuring WSS
        server {
                listen 8008;
                listen 8443 ssl;
                server_name demo-server.com;
                ssl_certificate server.pem;
                ssl_certificate_key server.key;
                location / {
                        proxy_pass http://unix:/tmp/accessws.sock;
                        proxy_redirect off;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                        proxy_send_timeout 1d;
                        proxy_read_timeout 1d;
                        proxy_connect_timeout 1d;
                        proxy_set_header X-Real-IP $remote_addr;
                }
        }
```

I connected over port 8443 since that is the SSL port for accessing wss:// and the Nginx has an error log record regarding the attempted access:

`*1 connect() to unix:/tmp/accessws.sock failed (111: Connection refused) while connecting to upstream, client: <client-ip>, server: demo-server.com, request: "GET /?encoding=text HTTP/1.1", upstream: "http://unix:/tmp/accessws.sock:/?encoding=text", host: "demo-server.com:8443"`

The error appears and WSS access attempt fails. I am guessing that the WSS access from 8443 via Nginx failed and thus did not proceed further to the accessws socket ?

Any solution to fix the above error and get the WSS up and running ?

**Comment by thotheolh** [comment]
Found the solution.

proxy_pass http://unix:/tmp/accessws.sock <--- replace and do not use unix socket.

Change it to:

proxy_pass http://<ip-address-of-normal-ws>:<port-of-normal-ws>

The reason is the complexity of permissions and so on around the unix socket is mind boggling and the normal WS port is working fine. So, redirecting the access from the Nginx Reverse Proxy to the working nomral WS port is a better option.

Additional note is now that now you have WSS and WS exposed, you might want to force users to only access the WSS secure service and close off WS but without terminating the Nginx Reverse Proxy access. What can be done is to edit the firewall rules to allow access to WS port for only localhost calls.

**Comment by wh0am111** [comment]
> Hello guys could you please share us how did you do the authentication of websocket? the url_auth has to be changed?

have you save the problem
 how?
